import { useNavigate } from "react-router-dom";
import { FileDown, FileText, FileJson, Printer } from "lucide-react";
import Navbar from "../components/layout/Navbar";

export default function Report() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-surfaceGray flex flex-col">
      <Navbar />
      <div className="flex flex-1">
        <main className="flex-1 flex justify-center py-10 px-6 overflow-y-auto">
          <div className="w-full max-w-[720px] bg-surface shadow-cardElevated rounded-sm p-12 text-[#0F172A]" style={{ aspectRatio: "1 / 1.414", minHeight: 900 }}>
            <div className="flex justify-between items-start border-b border-borderLight pb-4 mb-6">
              <div>
                <p className="text-lg font-bold text-primary">StructAI BasePlate</p>
                <p className="text-xs text-textMuted">Steel Base Plate Design Report</p>
              </div>
              <p className="text-xs text-textMuted">Preliminary</p>
            </div>

            <h1 className="text-2xl font-bold text-center mb-2">Steel Base Plate Design Report</h1>
            <p className="text-sm text-center text-textSecondary mb-10">
              Run a design in the Design Tool, then export a PDF to see your full 21-section report here.
            </p>

            <div className="text-center">
              <button
                onClick={() => navigate("/design")}
                className="px-6 py-3 rounded-btn bg-primary text-white text-sm font-medium hover:bg-primaryDark transition-all duration-150"
              >
                Go to Design Tool →
              </button>
            </div>

            <div className="mt-16 text-[11px] text-textMuted text-center italic leading-relaxed">
              This report is generated by StructAI BasePlate for preliminary design assistance only. Results must be
              reviewed, verified, and approved by a qualified structural engineer before use in construction or
              fabrication.
            </div>
          </div>
        </main>

        <aside className="w-[280px] shrink-0 hidden lg:block bg-surface border-l border-borderLight p-5">
          <p className="text-xs font-semibold text-textMuted uppercase tracking-wide mb-4">Export</p>
          <div className="space-y-2.5">
            <ExportRow icon={FileDown} label="Download PDF" />
            <ExportRow icon={FileText} label="Export TXT" />
            <ExportRow icon={FileJson} label="Export JSON" />
            <ExportRow icon={Printer} label="Print" />
          </div>
          <p className="text-xs text-textMuted mt-6 leading-relaxed">
            Complete a design in the Design Tool to enable exports here.
          </p>
        </aside>
      </div>
    </div>
  );
}

function ExportRow({ icon: Icon, label }: { icon: any; label: string }) {
  return (
    <button className="w-full flex items-center gap-2.5 px-4 py-2.5 rounded-input border border-borderMed bg-surface text-sm font-medium text-textSecondary hover:bg-surfaceGray transition-colors duration-150">
      <Icon size={16} />
      {label}
    </button>
  );
}
